title: Juan Ivan Cruz
logo: /assets/PP03.jpg
#description: Technical Manager with a strong focus on business goals and 14+ years of experience in Engineering. Skilled problem-solver, resource optimizer, and people developer. Achieved a manufacturing transfer involving automotive products, -61% in NPI set-up times, +15% in product FPA, and developed improved product prototypes.
show_downloads: true
theme: jekyll-theme-minimal
