title: Juan Ivan Cruz
logo: /assets/PP03.jpg
description: Technical Manager with a strong focus on business goals and 14+ years of experience in Engineering. Skilled problem-solver, resource optimizer, and people developer. Achieved a manufacturing transfer involving automotive products, -61% in NPI set-up times, +15% in product FPA, and developed prototypes that improved product performance.
---
##Languages
- Spanish :large_blue_circle: :large_blue_circle: :large_blue_circle: :large_blue_circle: :large_blue_circle:
- English :large_blue_circle: :large_blue_circle: :large_blue_circle: :large_blue_circle:
- Japanese :large_blue_circle: :large_blue_circle:


email: "juanivancruz@me.com"
show_downloads: false
theme: jekyll-theme-minimal
